In [1]:
import numpy as np

In [4]:
np.array([[1,2],[3,4]],dtype='int8')

array([[1, 2],
       [3, 4]], dtype=int8)

In [5]:
#ضرب ماتریسی با @ یا .dot
a=[[1,2],[3,4]]
b=np.array(a)
np.dot(b,b)

array([[ 7, 10],
       [15, 22]])

In [6]:
#numpy.multyply() ضرب عضو به عضو در ماتریس
# یا علامت *
a=[[1,2],[3,4]]
b=np.array(a)
b*b

array([[ 1,  4],
       [ 9, 16]])