# Numpy Examples

In [13]:
import numpy as np


In [14]:

np.array([[1,2],[3,4]],dtype='int8')

#ضرب ماتریسی با @ یا .dot
a=[[1,2],[3,4]]
b=np.array(a)
np.dot(b,b)


array([[ 7, 10],
       [15, 22]])

In [15]:

#numpy.multyply() ضرب عضو به عضو در ماتریس
# یا علامت *
a=[[1,2],[3,4]]
b=np.array(a)
b*b



array([[ 1,  4],
       [ 9, 16]])

In [16]:


#np.prod(b)  تمام اعضای ان را در هم ضرب میکند

np.prod(b)


24

In [17]:

# Broadcasting

#عدد 5 رو با تک تک درایه ها جمع کرد
my_array = np.array([1, 2, 3])
my_array + 5



array([6, 7, 8])

In [18]:

#ایجاد یک ارایه  سه در سه با تمام مقادیر یک
a=np.ones([3,3])
b=np.array([5,6,7])
#گسترش در جهت سطر ها
a+b



array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [19]:

#برودکستینگ همزمان برای دو ارایه:
a=np.ones((3,1))
b=np.array([5,6,7])
a+b



array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [20]:


#جمع و تفریق:

#جمع اعضای یک ارایه

a=[[1,2],[3,4]]

#جمع کردن اعضای ماتریس a
c=np.sum(a) 
print (c)

10


In [21]:


#جمع تجمعی
b=np.cumsum(a,axis=0) 
#axis=0 یعنی جمع برای سطر ها اتفاق میفته
#axis=1 یعنی جمع برای ستون ها اتفاق میفته
print(b)



[[1 2]
 [4 6]]


In [22]:


#np.subtract()تفریق

#تقسیم:
# تقسیم هر یک از عضو لیست بر سه
f=np.divide([5,6,7],3) 
print(f)


[1.66666667 2.         2.33333333]


In [23]:

# اعداد رو به پاییین گرد میکنه
g=np.floor_divide([5,6,7],3)
print(g)






[1 2 2]
